# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Android settings
android.useAndroidX=true
android.nonTransitiveRClass=true
android.disallowKotlinSourceSets=false

# Kotlin settings
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048m

# Compose settings
android.enableJetifier=false